Renaming fixes

diff --git a/dmenu-nm b/dmenu-nm
--- a/dmenu-nm
+++ b/dmenu-nm
@@ -5,7 +5,7 @@ nm-openvpn-up () { \
 
 	state=$(nmcli con up $connection)
 	#if [ -n $(echo "state" | grep success ] 
-	notify-send "nm-dmenu" "VPN connected to $connection"
+	notify-send "dmenu-nm" "VPN connected to $connection"
 }
 
 nm-openvpn-down () { \
@@ -22,7 +22,7 @@ nm-openvpn-resolve () { \
 	case $chosen in
 		Up) nm-vpn-up;;
 		Down) nm-vpn-down;;
-		*) notify-send -u critical "nm-dmenu" "Could not resolve management string for VPN";;
+		*) notify-send -u critical "dmenu-nm" "Could not resolve management string for VPN";;
 	esac
 }
 
@@ -31,11 +31,11 @@ nm-wireguard-up () { \
 
 	valid=$(ls /etc/wireguard/ | grep $vpn)
 
-	[ -z "$vpn" ] && notify-send -u critical "dmenu-wireguard" "No VPN chosen" && exit 1
+	[ -z "$vpn" ] && notify-send -u critical "dmenu-nm" "No VPN chosen" && exit 1
 
-	[ -z "$valid" ] && notify-send -u critical "dmenu-wireguard" "Invalid VPN chosen" && exit 1
+	[ -z "$valid" ] && notify-send -u critical "dmenu-nm" "Invalid VPN chosen" && exit 1
 
-	sudo -A wg-quick up $vpn && notify-send "dmenu-wireguard" " Connected to $vpn"
+	sudo -A wg-quick up $vpn && notify-send "dmenu-nm" " Connected to $vpn"
 }
 
 nm-wireguard-down () { \
@@ -43,11 +43,11 @@ nm-wireguard-down () { \
 
 	valid=$(wg show interfaces | grep $vpn)
 
-	[ -z "$vpn" ] && notify-send -u critical "dmenu-wireguard" "No VPN chosen" && exit 1
+	[ -z "$vpn" ] && notify-send -u critical "dmenu-nm" "No VPN chosen" && exit 1
 
-	[ -z "$valid" ] && notify-send -u critical "dmenu-wireguard" "Invalid VPN Chosen" && exit 1
+	[ -z "$valid" ] && notify-send -u critical "dmenu-nm" "Invalid VPN Chosen" && exit 1
 
-	sudo -A wg-quick down $vpn && notify-send "dmenu-wireguard" "Disconnected from $vpn"
+	sudo -A wg-quick down $vpn && notify-send "dmenu-nm" "Disconnected from $vpn"
 }
 
 nm-wireguard-resolve () { \
@@ -56,32 +56,32 @@ nm-wireguard-resolve () { \
 	case $chosen in
 		Up) nm-wireguard-up;;
 		Down) nm-wireguard-down;;
-		*) notify-send -u critical "dmenu-wireguard" "Could not resolve management string for WireGuard"
+		*) notify-send -u critical "dmenu-nm" "Could not resolve management string for WireGuard"
 	esac
 }
 
 nm-device-resolve () { \
 	act=$(echo -e 'connect\ndelete\ndisconnect' | dmenu -i -p 'Device Operation:' -fn 'hack-9' -nb '#1c2023' -nf '#f3f4f5' -sb '#ae95c7' -sf '#1c2023')
-	[ -z "$act" ] && notify-send -u critical "nm-dmenu" "No device operation specified" && exit 1
+	[ -z "$act" ] && notify-send -u critical "dmenu-nm" "No device operation specified" && exit 1
 
 	chosen=$(nmcli device | tail -n +2 | awk '{print $1}' | dmenu -i -p 'Device:' -fn 'hack-9' -nb '#1c2023' -nf '#f3f4f5' -sb '#ae95c7' -sf '#1c2023')
-	[ -z "$chosen" ] && notify-send -u critical "nm-dmenu" "No device specified" && exit 1
+	[ -z "$chosen" ] && notify-send -u critical "dmenu-nm" "No device specified" && exit 1
 
 	output=$(nmcli device $act "$chosen")
-	[ -z "$(echo $output | grep -iv error)" ] && notify-send -u critical "nm-dmenu" "Device error:\n$output" && exit 1
-	notify-send "nm-dmenu" "Device $act $chosen"
+	[ -z "$(echo $output | grep -iv error)" ] && notify-send -u critical "dmenu-nm" "Device error:\n$output" && exit 1
+	notify-send "dmenu-nm" "Device $act $chosen"
 }
 
 nm-connection-resolve () { \
 	act=$(echo -e 'up\ndown' | dmenu -i -p 'Connection Operation:' -fn 'hack-9' -nb '#1c2023' -nf '#f3f4f5' -sb '#ae95c7' -sf '#1c2023')
-	[ -z "$act" ] && notify-send -u critical "nm-dmenu" "No connection operation specified" && exit 1
+	[ -z "$act" ] && notify-send -u critical "dmenu-nm" "No connection operation specified" && exit 1
 
 	chosen=$(nmcli connection | grep -iv vpn | tail -n +2 | awk -F'   ' '{print $1}' | dmenu -i -p 'Connection:' -fn 'hack-9' -nb '#1c2023' -nf '#f3f4f5' -sb '#ae95c7' -sf '#1c2023')
-	[ -z "$chosen" ] && notify-send -u critical "nm-dmenu" "No connection specified" && exit 1
+	[ -z "$chosen" ] && notify-send -u critical "dmenu-nm" "No connection specified" && exit 1
 
 	output=$(nmcli connection $act "$chosen")
-	[ -z "$(echo $output | grep -iv error)" ] && notify-send -u critical "nm-dmenu" "Connection error:\n$output" && exit 1
-	notify-send "nm-dmenu" "Connection $act $chosen"
+	[ -z "$(echo $output | grep -iv error)" ] && notify-send -u critical "dmenu-nm" "Connection error:\n$output" && exit 1
+	notify-send "dmenu-nm" "Connection $act $chosen"
 }
 
 chosen=$(echo -e 'Device\nConnection\nVPN\nBluetooth' | dmenu -i -p 'Type to Manage:' -fn 'Hack-9' -nb '#1c2023' -nf '#f3f4f5' -sb '#ae95c7' -sf '#1c2023')
@@ -91,5 +91,5 @@ case $chosen in
 	Connection) nm-connection-resolve;;
 	VPN) nm-wireguard-resolve;;
 	Bluetooth) nm-bt-resolve;;
-	*) notify-send -u critical "nm-dmenu" "Could not resolve management string"
+	*) notify-send -u critical "dmenu-nm" "Could not resolve management string"
 esac
